apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: airflow
  name: airflow-worker-benchmark-w1-d16-stage-07
  annotations:
    dag_id: benchmark_w1_d16
    task_id: stage_07
spec:
  template:
    spec:
      containers:
        - image: "nehalem90/airflow-worker:latest"
          imagePullPolicy: Always
          ports:
            - name: h2c
              containerPort: 50000
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW_IS_K8S_EXECUTOR_POD
              value: "True"
            - name: AIRFLOW_DAG_ID
              value: benchmark_w1_d16
            - name: AIRFLOW_TASK_ID
              value: stage_07
            # Hard Coded Airflow Envs
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-metadata
                  key: connection
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-metadata
                  key: connection
            - name: AIRFLOW_CONN_AIRFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-metadata
                  key: connection
