apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: airflow
  name: airflow-worker-dag-w1-d32-func-1-12
  annotations:
    dag_id: dag_w1_d32
    task_id: func_1_12
spec:
  template:
    spec:
      containers:
        - image: "wanghanchengchn/airflow-worker:latest"
          imagePullPolicy: Always
          ports:
            - name: h2c
              containerPort: 50000
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW_IS_K8S_EXECUTOR_POD
              value: "True"
            - name: AIRFLOW_DAG_ID
              value: dag_w1_d32
            - name: AIRFLOW_TASK_ID
              value: func_1_12
            # Hard Coded Airflow Envs
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-metadata
                  key: connection
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-metadata
                  key: connection
            - name: AIRFLOW_CONN_AIRFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-metadata
                  key: connection
    metadata:
      annotations:
        autoscaling.knative.dev/window: "60s"
        autoscaling.knative.dev/minScale: "1"
