# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import remote_xcom_pb2 as remote__xcom__pb2


class TaskRunStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleTask = channel.unary_unary(
                '/Remote_xcom.TaskRun/HandleTask',
                request_serializer=remote__xcom__pb2.task_invoke.SerializeToString,
                response_deserializer=remote__xcom__pb2.task_reply.FromString,
                )


class TaskRunServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandleTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskRunServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleTask': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleTask,
                    request_deserializer=remote__xcom__pb2.task_invoke.FromString,
                    response_serializer=remote__xcom__pb2.task_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Remote_xcom.TaskRun', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskRun(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandleTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Remote_xcom.TaskRun/HandleTask',
            remote__xcom__pb2.task_invoke.SerializeToString,
            remote__xcom__pb2.task_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
