# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_xcom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11remote_xcom.proto\x12\x0bRemote_xcom\"\x1b\n\x0btask_invoke\x12\x0c\n\x04\x61rgs\x18\x01 \x03(\t\"\x1c\n\ntask_reply\x12\x0e\n\x06timing\x18\x01 \x01(\x0c\x32L\n\x07TaskRun\x12\x41\n\nHandleTask\x12\x18.Remote_xcom.task_invoke\x1a\x17.Remote_xcom.task_reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_xcom_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TASK_INVOKE']._serialized_start=34
  _globals['_TASK_INVOKE']._serialized_end=61
  _globals['_TASK_REPLY']._serialized_start=63
  _globals['_TASK_REPLY']._serialized_end=91
  _globals['_TASKRUN']._serialized_start=93
  _globals['_TASKRUN']._serialized_end=169
# @@protoc_insertion_point(module_scope)
