apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: airflow
  name: airflow-workflow-gateway
spec:
  template:
    spec:
      containers:
        - image: "ghcr.io/jonamuen/airflow-workflow-gateway:latest"
          imagePullPolicy: Always
          ports:
            - name: http1
              containerPort: 8081
